FROM node:22-alpine as builder

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn install

COPY . /app/

ENV NODE_OPTIONS="--max-old-space-size=8192"

RUN VITE_REACT_APP_API_URL=https://test.eosi.kz npm run build:dev

FROM macbre/nginx-brotli:1.19.6-http3

EXPOSE 80

WORKDIR /app

COPY default.nginx /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
