/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ResponsesActResponse } from './responsesActResponse';

export interface ApiResponse1OSICoreModelsResponsesActResponse {
  code?: number;
  /** @nullable */
  message?: string | null;
  result?: ResponsesActResponse;
}
