/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbOsiAccount } from './dbOsiAccount';

export interface ApiResponse1OSICoreModelsDbOsiAccount {
  code?: number;
  /** @nullable */
  message?: string | null;
  result?: DbOsiAccount;
}
