/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ResponsesUserAffiliation } from './responsesUserAffiliation';

export interface ApiResponse1SystemCollectionsGenericIEnumerable1OSICoreModelsResponsesUserAffiliation {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: ResponsesUserAffiliation[] | null;
}
