/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbServiceCompany } from './dbServiceCompany';

export interface ApiResponse1SystemCollectionsGenericIEnumerable1OSICoreModelsDbServiceCompany {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: DbServiceCompany[] | null;
}
