/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ResponsesServiceGroupSaldoResponse } from './responsesServiceGroupSaldoResponse';

export interface ApiResponse1SystemCollectionsGenericIEnumerable1OSICoreModelsResponsesServiceGroupSaldoResponse {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: ResponsesServiceGroupSaldoResponse[] | null;
}
