/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbUnionType } from './dbUnionType';

export interface ApiResponse1SystemCollectionsGenericIEnumerable1OSICoreModelsDbUnionType {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: DbUnionType[] | null;
}
