/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbServiceGroup } from './dbServiceGroup';

export interface ApiResponse1SystemCollectionsGenericIEnumerable1OSICoreModelsDbServiceGroup {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: DbServiceGroup[] | null;
}
