/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbAccountReport } from './dbAccountReport';

export interface ApiResponse1SystemCollectionsGenericIEnumerable1OSICoreModelsDbAccountReport {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: DbAccountReport[] | null;
}
