/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbOsiService } from './dbOsiService';

export interface ApiResponse1SystemCollectionsGenericIEnumerable1OSICoreModelsDbOsiService {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: DbOsiService[] | null;
}
