/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ReportsSaldoOnAllPeriodSaldoPeriod } from './reportsSaldoOnAllPeriodSaldoPeriod';

export interface ApiResponse1SystemCollectionsGenericIEnumerable1OSICoreModelsReportsSaldoOnAllPeriodSaldoPeriod {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: ReportsSaldoOnAllPeriodSaldoPeriod[] | null;
}
