/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbAccuralMethod } from './dbAccuralMethod';

export interface ApiResponse1SystemCollectionsGenericIEnumerable1OSICoreModelsDbAccuralMethod {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: DbAccuralMethod[] | null;
}
