/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ResponsesUserContactResponse } from './responsesUserContactResponse';

export interface ApiResponse1OSICoreModelsResponsesUserContactResponse {
  code?: number;
  /** @nullable */
  message?: string | null;
  result?: ResponsesUserContactResponse;
}
