/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface ApiResponse {
  code?: number;
  /** @nullable */
  message?: string | null;
}
