/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbActDoc } from './dbActDoc';

export interface ApiResponse1OSICoreModelsDbActDoc {
  code?: number;
  /** @nullable */
  message?: string | null;
  result?: DbActDoc;
}
