/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbOsiAccountApplication } from './dbOsiAccountApplication';

export interface ApiResponse1OSICoreModelsDbOsiAccountApplication {
  code?: number;
  /** @nullable */
  message?: string | null;
  result?: DbOsiAccountApplication;
}
