/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ResponsesAccountReportFormData } from './responsesAccountReportFormData';

export interface ApiResponse1OSICoreModelsResponsesAccountReportFormData {
  code?: number;
  /** @nullable */
  message?: string | null;
  result?: ResponsesAccountReportFormData;
}
