/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ResponsesAbonentOnServiceResponse } from './responsesAbonentOnServiceResponse';

export interface ApiResponse1SystemCollectionsGenericList1OSICoreModelsResponsesAbonentOnServiceResponse {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: ResponsesAbonentOnServiceResponse[] | null;
}
