/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbServiceGroupSaldo } from './dbServiceGroupSaldo';

export interface ApiResponse1OSICoreModelsDbServiceGroupSaldo {
  code?: number;
  /** @nullable */
  message?: string | null;
  result?: DbServiceGroupSaldo;
}
