/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ReportsPaymentTransaction } from './reportsPaymentTransaction';

export interface ApiResponse1SystemCollectionsGenericList1OSICoreModelsReportsPaymentTransaction {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: ReportsPaymentTransaction[] | null;
}
