/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbAreaType } from './dbAreaType';

export interface ApiResponse1SystemCollectionsGenericIEnumerable1OSICoreModelsDbAreaType {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: DbAreaType[] | null;
}
