/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbOsi } from './dbOsi';

export interface ApiResponse1SystemCollectionsGenericIEnumerable1OSICoreModelsDbOsi {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: DbOsi[] | null;
}
