/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbAct } from './dbAct';

export interface ApiResponse1SystemCollectionsGenericIEnumerable1OSICoreModelsDbAct {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: DbAct[] | null;
}
