/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbDocType } from './dbDocType';

export interface ApiResponse1SystemCollectionsGenericIEnumerable1OSICoreModelsDbDocType {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: DbDocType[] | null;
}
