/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { BanksNotProcessedPayment } from './banksNotProcessedPayment';

export interface ApiResponse1SystemCollectionsGenericIEnumerable1OSICoreModelsBanksNotProcessedPayment {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: BanksNotProcessedPayment[] | null;
}
