/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ResponsesDebtorNotificationResponse } from './responsesDebtorNotificationResponse';

export interface ApiResponse1OSICoreModelsResponsesDebtorNotificationResponse {
  code?: number;
  /** @nullable */
  message?: string | null;
  result?: ResponsesDebtorNotificationResponse;
}
