/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ReportsSvodPaymentOrder } from './reportsSvodPaymentOrder';

export interface ApiResponse1SystemCollectionsGenericIEnumerable1OSICoreModelsReportsSvodPaymentOrder {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: ReportsSvodPaymentOrder[] | null;
}
