/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ApiResponse1SystemObjectResult } from './apiResponse1SystemObjectResult';

export interface ApiResponse1SystemObject {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: ApiResponse1SystemObjectResult;
}
