/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbPlanAccural } from './dbPlanAccural';

export interface ApiResponse1SystemCollectionsGenericIEnumerable1OSICoreModelsDbPlanAccural {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: DbPlanAccural[] | null;
}
