/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbAccountReportList } from './dbAccountReportList';

export interface ApiResponse1OSICoreModelsDbAccountReportList {
  code?: number;
  /** @nullable */
  message?: string | null;
  result?: DbAccountReportList;
}
