/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ResponsesUserResponse } from './responsesUserResponse';

export interface ApiResponse1OSICoreModelsResponsesUserResponse {
  code?: number;
  /** @nullable */
  message?: string | null;
  result?: ResponsesUserResponse;
}
