/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ResponsesEndSaldoResponse } from './responsesEndSaldoResponse';

export interface ApiResponse1OSICoreModelsResponsesEndSaldoResponse {
  code?: number;
  /** @nullable */
  message?: string | null;
  result?: ResponsesEndSaldoResponse;
}
