/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbAbonent } from './dbAbonent';

export interface ApiResponse1SystemCollectionsGenericList1OSICoreModelsDbAbonent {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: DbAbonent[] | null;
}
