/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbKnp } from './dbKnp';

export interface ApiResponse1SystemCollectionsGenericIEnumerable1OSICoreModelsDbKnp {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: DbKnp[] | null;
}
