/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbArendator } from './dbArendator';

export interface ApiResponse1OSICoreModelsDbArendator {
  code?: number;
  /** @nullable */
  message?: string | null;
  result?: DbArendator;
}
