/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbOsiAccountApplicationDoc } from './dbOsiAccountApplicationDoc';

export interface ApiResponse1SystemCollectionsGenericIEnumerable1OSICoreModelsDbOsiAccountApplicationDoc {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  result?: DbOsiAccountApplicationDoc[] | null;
}
