/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ReportsOSV } from './reportsOSV';

export interface ApiResponse1OSICoreModelsReportsOSV {
  code?: number;
  /** @nullable */
  message?: string | null;
  result?: ReportsOSV;
}
