/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface BanksNotProcessedPayment {
  /** @nullable */
  abonentNum?: string | null;
  amount?: number;
  paymentDate?: string;
  paymentId?: number;
  /** @nullable */
  reference?: string | null;
}
