/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { EnumsAccountTypeCodes } from './enumsAccountTypeCodes';

export interface DbAccountType {
  code?: EnumsAccountTypeCodes;
  /**
   * @maxLength 100
   * @nullable
   */
  nameKz?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  nameRu?: string | null;
}
