/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { EnumsActStateCodes } from './enumsActStateCodes';

export interface DbAct {
  /** @nullable */
  readonly actDateStr?: string | null;
  /** @maxLength 30 */
  actNum: string;
  actPeriod?: string;
  amount?: number;
  /** @nullable */
  readonly apartCount?: number | null;
  comission?: number;
  createDt?: string;
  debt?: number;
  /** @nullable */
  esfError?: string | null;
  /** @nullable */
  esfNum?: string | null;
  id?: number;
  /** @nullable */
  readonly osiAddress?: string | null;
  osiId?: number;
  /** @nullable */
  readonly osiIdn?: string | null;
  /** @nullable */
  readonly osiName?: string | null;
  /** @nullable */
  readonly osiPhone?: string | null;
  /** @nullable */
  readonly osiRegistrationDate?: string | null;
  planAccuralId?: number;
  /** @nullable */
  signDt?: string | null;
  stateCode: EnumsActStateCodes;
  /** @nullable */
  readonly stateName?: string | null;
  tariff?: number;
}
