/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface DbActItem {
  amount?: number;
  dateWork?: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  note?: string | null;
  price?: number;
  quantity?: number;
}
