/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { EnumsAccountTypeCodes } from './enumsAccountTypeCodes';
import type { DbAccountReportListItem } from './dbAccountReportListItem';

export interface DbAccountReportList {
  /**
   * @maxLength 20
   * @nullable
   */
  account?: string | null;
  accountType?: EnumsAccountTypeCodes;
  /** @nullable */
  readonly accountTypeNameKz?: string | null;
  /** @nullable */
  readonly accountTypeNameRu?: string | null;
  /** @nullable */
  readonly bankName?: string | null;
  /** @nullable */
  readonly bankStatementVideoUrl?: string | null;
  begin?: number;
  /** @nullable */
  bic?: string | null;
  debet?: number;
  end?: number;
  id?: number;
  isFilled?: boolean;
  /** @nullable */
  isInPublishedReport?: boolean | null;
  /** @nullable */
  readonly items?: readonly DbAccountReportListItem[] | null;
  kredit?: number;
  period?: string;
}
