/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface DbAccountReportListItemDetail {
  amount?: number;
  categoryId: number;
  /**
   * @minLength 6
   * @maxLength 500
   * @nullable
   */
  comment?: string | null;
  id?: number;
}
