/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbAccountReportListItemDetail } from './dbAccountReportListItemDetail';
import type { EnumsOperationTypeCodes } from './enumsOperationTypeCodes';

export interface DbAccountReportListItem {
  amount?: number;
  /**
   * @maxLength 1000
   * @nullable
   */
  assign?: string | null;
  /** @nullable */
  categoryId?: number | null;
  /** @nullable */
  details?: DbAccountReportListItemDetail[] | null;
  dt?: string;
  id?: number;
  operationType?: EnumsOperationTypeCodes;
  /** @nullable */
  readonly operationTypeNameKz?: string | null;
  /** @nullable */
  readonly operationTypeNameRu?: string | null;
  /**
   * @maxLength 500
   * @nullable
   */
  receiver?: string | null;
  /**
   * @maxLength 12
   * @nullable
   */
  receiverBin?: string | null;
  /**
   * @maxLength 500
   * @nullable
   */
  sender?: string | null;
  /**
   * @maxLength 12
   * @nullable
   */
  senderBin?: string | null;
}
