/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface DbArendator {
  abonentId?: number;
  /** @nullable */
  address?: string | null;
  id?: number;
  rca: string;
}
