/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface DbBank {
  /**
   * @maxLength 10
   * @nullable
   */
  bic?: string | null;
  /**
   * @maxLength 10
   * @nullable
   */
  identifier?: string | null;
  /**
   * @maxLength 200
   * @nullable
   */
  name?: string | null;
}
