/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface DbDocType {
  /** @maxLength 50 */
  code: string;
  maxSize: number;
  /**
   * @maxLength 100
   * @nullable
   */
  nameKz?: string | null;
  /** @maxLength 100 */
  nameRu: string;
}
