/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { EnumsHouseStateCodes } from './enumsHouseStateCodes';

export interface DbHouseState {
  code?: EnumsHouseStateCodes;
  /**
   * @maxLength 50
   * @nullable
   */
  nameKz?: string | null;
  /**
   * @maxLength 50
   * @nullable
   */
  nameRu?: string | null;
}
