/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface DbOsiService {
  accuralMethodId?: number;
  amount?: number;
  readonly copyToNextPeriod?: boolean;
  id?: number;
  isActive: boolean;
  isOsibilling: boolean;
  /** @nullable */
  nameKz?: string | null;
  nameRu: string;
  osiId: number;
  serviceGroupId?: number;
  /** @nullable */
  readonly serviceGroupNameKz?: string | null;
  /** @nullable */
  readonly serviceGroupNameRu?: string | null;
}
