/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { EnumsHouseStateCodes } from './enumsHouseStateCodes';

export interface DbOsi {
  accuralsWithDecimals?: boolean;
  /** @maxLength 100 */
  address: string;
  /** @nullable */
  apartCount?: number | null;
  /**
   * @minimum 100
   * @maximum 300
   */
  coefUnlivingArea: number;
  /**
   * @maxLength 50
   * @nullable
   */
  constructionMaterial?: string | null;
  /** @nullable */
  constructionYear?: number | null;
  createFine?: boolean;
  /**
   * @maxLength 100
   * @nullable
   * @pattern ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$
   */
  email?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  fio?: string | null;
  /**
   * @minimum 1
   * @maximum 100
   * @nullable
   */
  floors?: number | null;
  freeMonthPromo?: number;
  /** @nullable */
  gasified?: boolean | null;
  houseStateCode?: EnumsHouseStateCodes;
  /** @nullable */
  readonly houseStateNameKz?: string | null;
  /** @nullable */
  readonly houseStateNameRu?: string | null;
  id?: number;
  /** @maxLength 12 */
  idn: string;
  isActive: boolean;
  isInPromo?: boolean;
  isLaunched: boolean;
  /**
   * @minLength 2
   * @maxLength 2
   */
  kbe: string;
  /** @maxLength 100 */
  name: string;
  /** @nullable */
  personalElectricPower?: boolean | null;
  /** @nullable */
  personalHeating?: boolean | null;
  /** @nullable */
  personalHotWater?: boolean | null;
  /**
   * @maxLength 15
   * @pattern ^7\d{9}$
   */
  phone: string;
  /**
   * @maxLength 16
   * @nullable
   */
  rca?: string | null;
  registrationId: number;
  /** @nullable */
  registrationType?: string | null;
  takeComission?: boolean;
  unionTypeId: number;
  /** @nullable */
  readonly unionTypeKz?: string | null;
  /** @nullable */
  readonly unionTypeRu?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  wizardStep?: string | null;
}
