/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { EnumsAccountTypeCodes } from './enumsAccountTypeCodes';

export interface DbOsiAccountApplication {
  /** @maxLength 20 */
  account: string;
  /** @nullable */
  readonly accountTypeNameKz?: string | null;
  /** @nullable */
  readonly accountTypeNameRu?: string | null;
  /** @nullable */
  applicationType?: string | null;
  /** @nullable */
  readonly applicationTypeText?: string | null;
  /** @nullable */
  readonly bankName?: string | null;
  bic: string;
  createDt?: string;
  id?: number;
  /** @nullable */
  oldAccount?: string | null;
  /** @nullable */
  oldBankBic?: string | null;
  /** @nullable */
  osiAccountId?: number | null;
  osiId: number;
  /** @nullable */
  rejectReason?: string | null;
  /** @nullable */
  serviceGroupId?: number | null;
  /** @nullable */
  state?: string | null;
  /** @nullable */
  readonly stateText?: string | null;
  type: EnumsAccountTypeCodes;
}
