/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { EnumsRegistrationStateCodes } from './enumsRegistrationStateCodes';

export interface DbRegistration {
  /** @maxLength 100 */
  address: string;
  /** @nullable */
  addressRegistryId?: number | null;
  /**
   * @minimum 1
   * @maximum 999
   */
  apartCount: number;
  /** @nullable */
  atsId?: number | null;
  createDt?: string;
  /**
   * @maxLength 100
   * @nullable
   * @pattern ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$
   */
  email?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  fio?: string | null;
  id?: number;
  /** @maxLength 12 */
  idn: string;
  /** @maxLength 100 */
  name: string;
  /**
   * @maxLength 15
   * @pattern ^7\d{9}$
   */
  phone: string;
  /**
   * @maxLength 16
   * @nullable
   */
  rca?: string | null;
  /** @nullable */
  registrationKind?: string | null;
  /** @nullable */
  registrationType?: string | null;
  /** @nullable */
  rejectReason?: string | null;
  /** @nullable */
  reqTypeCode?: string | null;
  /** @nullable */
  signDt?: string | null;
  stateCode: EnumsRegistrationStateCodes;
  /** @nullable */
  readonly stateName?: string | null;
  tariff?: number;
  unionTypeId?: number;
  /** @nullable */
  readonly unionTypeKz?: string | null;
  /** @nullable */
  readonly unionTypeRu?: string | null;
  userId: number;
  /**
   * @maxLength 20
   * @nullable
   */
  wizardStep?: string | null;
}
