/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface DbServiceCompany {
  /** @nullable */
  code?: string | null;
  /**
   * @maxLength 200
   * @nullable
   */
  nameKz?: string | null;
  /**
   * @maxLength 200
   * @nullable
   */
  nameRu?: string | null;
}
