/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface DbServiceGroupSaldo {
  /** @nullable */
  abonentFlat?: string | null;
  abonentId?: number;
  /** @nullable */
  abonentName?: string | null;
  groupId?: number;
  /** @nullable */
  readonly groupNameKz?: string | null;
  /** @nullable */
  readonly groupNameRu?: string | null;
  id?: number;
  osiId?: number;
  saldo?: number;
  transactionId?: number;
}
