/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface DbUnionType {
  id?: number;
  /**
   * @maxLength 100
   * @nullable
   */
  nameKz?: string | null;
  /** @nullable */
  nameRu?: string | null;
}
