/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export type EnumsActStateCodes = (typeof EnumsActStateCodes)[keyof typeof EnumsActStateCodes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnumsActStateCodes = {
  CREATED: 'CREATED',
  SIGNED: 'SIGNED',
  PROV: 'PROV'
} as const;
