/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export type EnumsAccountTypeCodes = (typeof EnumsAccountTypeCodes)[keyof typeof EnumsAccountTypeCodes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnumsAccountTypeCodes = {
  CURRENT: 'CURRENT',
  SAVINGS: 'SAVINGS'
} as const;
