/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export type EnumsOperationTypeCodes = (typeof EnumsOperationTypeCodes)[keyof typeof EnumsOperationTypeCodes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnumsOperationTypeCodes = {
  DEBET: 'DEBET',
  KREDIT: 'KREDIT'
} as const;
