/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { EnumsDebtFileTypeCodes } from './enumsDebtFileTypeCodes';

export type GetApiReportsDebtFileCurrentMonthOsiIdParams = {
  /**
   * Тип файла
   */
  debtFileType: EnumsDebtFileTypeCodes;
};
