/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export type GetApiPastDebtsNotaryApplicationParams = {
  /**
   * Id абонента
   */
  abonentId: number;
};
