/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export type GetApiReportsFileForCheckActsParams = {
  /**
   * Дата планов начислений - первое число предыдущего месяца
   */
  onDate: string;
};
