/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export type GetApiTransactionsOsvForDebtorsOsiIdParams = {
  /**
   * Начало периода
   */
  dateBegin: string;
  /**
   * Конец периода
   */
  dateEnd: string;
};
