/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export type PostApiTransactionsFineParams = {
  /**
   * Id ОСИ
   */
  osiId: number;
  /**
   * Год
   */
  year: number;
  /**
   * Месяц
   */
  month: number;
};
