/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export type PostApiUsersIdClearAllInformationParams = {
  /**
   * Пароль "удалить" на англ. раскладке
   */
  password: string;
};
