/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export type PostApiAuthParams = {
  /**
   * Имя пользователя (для председателей это номер телефона)
   */
  username?: string;
  /**
   * Постоянный пароль
   */
  password?: string;
};
