/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export type PostApiReportsAbonentsInvoicesPdfOnPeriodParams = {
  /**
   * Год
   */
  year: number;
  /**
   * Месяц
   */
  month: number;
  /**
   * Прямой (true) или сквозной (false) порядок абонентов
   */
  isStraightOrder: boolean;
  /**
   * Только резиденты и подвалы (true) или все абоненты (false)
   */
  isOnlyResidents: boolean;
};
