/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export type PutApiBuhCreateEsfsParams = {
  /**
   * Год
   */
  year?: number;
  /**
   * Месяц, обычно передаем предыдущий
   */
  month?: number;
};
