/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface ReportsAccuralsByAbonentAndServicesService {
  accural?: number;
  fix?: number;
  /** @nullable */
  serviceName?: string | null;
  total?: number;
}
