/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface ReportsPaymentTransaction {
  /** @nullable */
  abonentName?: string | null;
  amount?: number;
  /** @nullable */
  bankName?: string | null;
  dt?: string;
  /** @nullable */
  flat?: string | null;
  /** @nullable */
  serviceName?: string | null;
}
