/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface ReportsSvodPaymentOrder {
  amount?: number;
  amountToTransfer?: number;
  /** @nullable */
  bankName?: string | null;
  comisBank?: number;
  comisOur?: number;
  date?: string;
  /** @nullable */
  iban?: string | null;
}
