/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ReportsOSVAbonent } from './reportsOSVAbonent';

export interface ReportsOSV {
  /** @nullable */
  abonents?: ReportsOSVAbonent[] | null;
}
