/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { EnumsAreaTypeCodes } from './enumsAreaTypeCodes';
import type { ReportsOSVSaldo } from './reportsOSVSaldo';

export interface ReportsOSVAbonent {
  abonentId?: number;
  /** @nullable */
  abonentName?: string | null;
  areaTypeCode?: EnumsAreaTypeCodes;
  /** @nullable */
  flat?: string | null;
  isActive?: boolean;
  /** @nullable */
  owner?: string | null;
  /** @nullable */
  readonly services?: readonly ReportsOSVSaldo[] | null;
}
