/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface ReportsSaldoOnAllPeriodSaldoPeriodItemFix {
  amount?: number;
  dt?: string;
  /** @nullable */
  reason?: string | null;
}
