/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ReportsSaldoOnAllPeriodSaldoPeriodItem } from './reportsSaldoOnAllPeriodSaldoPeriodItem';

export interface ReportsSaldoOnAllPeriodSaldoPeriod {
  /** @nullable */
  period?: string | null;
  /** @nullable */
  services?: ReportsSaldoOnAllPeriodSaldoPeriodItem[] | null;
}
