/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface RequestsServiceGroupSaldoRequest {
  abonentId?: number;
  groupId?: number;
  osiId?: number;
  saldo?: number;
}
