/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { EnumsAreaTypeCodes } from './enumsAreaTypeCodes';

export interface RequestsAbonentRequest {
  areaTypeCode: EnumsAreaTypeCodes;
  /** @nullable */
  effectiveSquare?: number | null;
  external?: boolean;
  /** @maxLength 200 */
  flat: string;
  floor: number;
  /** @nullable */
  idn?: string | null;
  livingFact: number;
  livingJur: number;
  /**
   * @maxLength 100
   * @nullable
   */
  name?: string | null;
  osiId?: number;
  /** @nullable */
  owner?: string | null;
  /**
   * @maxLength 15
   * @nullable
   * @pattern ^7\d{9}$
   */
  phone?: string | null;
  square: number;
}
