/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface RequestsResetPasswordRequest {
  confirmPassword: string;
  newPassword: string;
  otp: string;
}
