/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface RequestsArendatorRequest {
  /** @nullable */
  address?: string | null;
  flat: string;
  /** @nullable */
  idn?: string | null;
  /** @nullable */
  name?: string | null;
  osiId?: number;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  rca?: string | null;
}
