/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { RequestsPaymentService } from './requestsPaymentService';

export interface RequestsCreatePaymentRequest {
  abonentNum: string;
  date?: string;
  reference: string;
  services: RequestsPaymentService[];
}
