/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface RequestsOsiServiceCompanyRequest {
  /** @nullable */
  addresses?: string | null;
  osiId: number;
  phones: string;
  serviceCompanyCode: string;
  showPhones?: boolean;
}
