/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { EnumsHouseStateCodes } from './enumsHouseStateCodes';

export interface RequestsOsiRequest {
  /** @maxLength 100 */
  address: string;
  /** @nullable */
  apartCount?: number | null;
  /**
   * @minimum 100
   * @maximum 300
   */
  coefUnlivingArea: number;
  /**
   * @maxLength 50
   * @nullable
   */
  constructionMaterial?: string | null;
  /** @nullable */
  constructionYear?: number | null;
  createFine?: boolean;
  /**
   * @maxLength 100
   * @nullable
   * @pattern ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$
   */
  email?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  fio?: string | null;
  /**
   * @minimum 1
   * @maximum 100
   * @nullable
   */
  floors?: number | null;
  /** @nullable */
  gasified?: boolean | null;
  houseStateCode?: EnumsHouseStateCodes;
  /** @maxLength 12 */
  idn: string;
  /** @maxLength 100 */
  name: string;
  /** @nullable */
  personalElectricPower?: boolean | null;
  /** @nullable */
  personalHeating?: boolean | null;
  /** @nullable */
  personalHotWater?: boolean | null;
  /**
   * @maxLength 15
   * @pattern ^7\d{9}$
   */
  phone: string;
  /** @nullable */
  registrationType?: string | null;
  unionTypeId: number;
}
