/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { RequestsFixService } from './requestsFixService';

export interface RequestsCreateFixRequest {
  abonentNum: number;
  /**
   * @minLength 7
   * @maxLength 500
   */
  reason: string;
  services: RequestsFixService[];
}
