/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface RequestsTelegramSendMessage {
  /** @nullable */
  message?: string | null;
  /** @nullable */
  phone?: string | null;
}
