/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface RequestsAddScanDoc {
  data: string;
  docTypeCode: string;
  /** @nullable */
  extension?: string | null;
}
