/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface ResponsesUserAffiliationAbonent {
  abonentId?: number;
  /** @nullable */
  abonentName?: string | null;
  /** @nullable */
  flat?: string | null;
}
