/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ResponsesNotaryApplicationRegistryItem } from './responsesNotaryApplicationRegistryItem';

export interface ResponsesNotaryApplicationRegistryGroup {
  /** @nullable */
  debts?: ResponsesNotaryApplicationRegistryItem[] | null;
  /** @nullable */
  serviceName?: string | null;
  /** @nullable */
  serviceNameKz?: string | null;
  readonly totalDebt?: number;
  /** @nullable */
  readonly totalDebtString?: string | null;
}
