/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ResponsesPastDebtInfo } from './responsesPastDebtInfo';

export interface ResponsesPastDebtsByOsiResponseItem {
  /** @nullable */
  pastDebts?: ResponsesPastDebtInfo[] | null;
  serviceGroupId?: number;
  /** @nullable */
  serviceGroupNameKz?: string | null;
  /** @nullable */
  serviceGroupNameRu?: string | null;
}
