/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { DbActItem } from './dbActItem';
import type { EnumsActStateCodes } from './enumsActStateCodes';

export interface ResponsesActResponse {
  /** @nullable */
  actItems?: DbActItem[] | null;
  /** @nullable */
  actNum?: string | null;
  actPeriod?: string;
  amount?: number;
  /** @nullable */
  readonly apartCount?: number | null;
  comission?: number;
  createDt?: string;
  debt?: number;
  id?: number;
  /** @nullable */
  readonly osiAddress?: string | null;
  /** @nullable */
  readonly osiIdn?: string | null;
  /** @nullable */
  readonly osiName?: string | null;
  /** @nullable */
  readonly osiPhone?: string | null;
  /** @nullable */
  readonly osiRegistrationDate?: string | null;
  planAccuralId?: number;
  /** @nullable */
  signDt?: string | null;
  stateCode?: EnumsActStateCodes;
  tariff?: number;
}
