/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ResponsesUserAffiliationAbonent } from './responsesUserAffiliationAbonent';

export interface ResponsesUserAffiliation {
  /** @nullable */
  abonents?: ResponsesUserAffiliationAbonent[] | null;
  /** @nullable */
  address?: string | null;
  osiId?: number;
  /** @nullable */
  osiName?: string | null;
}
