/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ResponsesDebtorNotificationResponseItem } from './responsesDebtorNotificationResponseItem';

export interface ResponsesDebtorNotificationResponse {
  /** @nullable */
  address?: string | null;
  debtDate?: string;
  /** @nullable */
  flat?: string | null;
  /** @nullable */
  osiChairman?: string | null;
  osiId?: number;
  /** @nullable */
  osiName?: string | null;
  /** @nullable */
  servicesDebts?: ResponsesDebtorNotificationResponseItem[] | null;
}
