/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ResponsesNotaryApplicationRegistryGroup } from './responsesNotaryApplicationRegistryGroup';

export interface ResponsesNotaryApplicationResponse {
  /** @nullable */
  abonentAddress?: string | null;
  /** @nullable */
  abonentFlat?: string | null;
  /** @nullable */
  abonentIdn?: string | null;
  /** @nullable */
  abonentName?: string | null;
  /** @nullable */
  abonentPhone?: string | null;
  debtDate?: string;
  /** @nullable */
  osiAddress?: string | null;
  /** @nullable */
  osiChairman?: string | null;
  osiId?: number;
  /** @nullable */
  osiIdn?: string | null;
  /** @nullable */
  osiName?: string | null;
  /** @nullable */
  osiPhone?: string | null;
  /** @nullable */
  registry?: ResponsesNotaryApplicationRegistryGroup[] | null;
  readonly totalDebt?: number;
  /** @nullable */
  readonly totalDebtString?: string | null;
}
