/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ResponsesServiceGroupSaldoResponseItem } from './responsesServiceGroupSaldoResponseItem';

export interface ResponsesServiceGroupSaldoResponse {
  groupId?: number;
  /** @nullable */
  groupNameKz?: string | null;
  /** @nullable */
  groupNameRu?: string | null;
  /** @nullable */
  items?: ResponsesServiceGroupSaldoResponseItem[] | null;
}
