/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ResponsesPastDebtsByOsiResponseItem } from './responsesPastDebtsByOsiResponseItem';

export interface ResponsesPastDebtsByOsiResponse {
  abonentId?: number;
  /** @nullable */
  abonentName?: string | null;
  /** @nullable */
  flat?: string | null;
  /** @nullable */
  serviceGroups?: ResponsesPastDebtsByOsiResponseItem[] | null;
}
