/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface ResponsesNotaryApplicationRegistryItem {
  cumulativeDebt?: number;
  debt?: number;
  number?: number;
  /** @nullable */
  period?: string | null;
}
