/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ResponsesRoleResponse } from './responsesRoleResponse';

export interface ResponsesUserResponse {
  /** @nullable */
  code?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  fio?: string | null;
  id?: number;
  /** @nullable */
  iin?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  roles?: ResponsesRoleResponse[] | null;
}
