/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */

export interface ResponsesDebtorNotificationResponseItem {
  saldo?: number;
  /** @nullable */
  readonly saldoString?: string | null;
  /** @nullable */
  serviceName?: string | null;
  /** @nullable */
  serviceNameKz?: string | null;
}
