/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import type { ResponsesAccountReportCategoryFormData } from './responsesAccountReportCategoryFormData';

export interface ResponsesAccountReportFormData {
  /** @nullable */
  categories?: ResponsesAccountReportCategoryFormData[] | null;
  /** @nullable */
  osiAddress?: string | null;
  /** @nullable */
  osiName?: string | null;
  period?: string;
  /** @nullable */
  signer?: string | null;
  /** @nullable */
  readonly unionTypeKz?: string | null;
  /** @nullable */
  readonly unionTypeRu?: string | null;
}
