/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OSI.Core
 * OpenAPI spec version: v1
 */
import { useMutation } from '@tanstack/react-query';
import type { MutationFunction, UseMutationOptions, UseMutationResult } from '@tanstack/react-query';
import type {
  ApiResponse1SystemString,
  PutApiBuhCreateAccuralsInCustomPeriodParams,
  PutApiBuhCreateAccuralsParams,
  PutApiBuhCreateActsParams,
  PutApiBuhCreateEsfsParams
} from '.././models';
import { axiosForReactQueryInstance } from '../../reactQuery';
import type { ErrorType } from '../../reactQuery';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * @summary Сделать начисления по всем планам начислений на текущий день (только по рабочим ОСИ)
 */
export const putApiBuhCreateAccurals = (
  params?: PutApiBuhCreateAccuralsParams,
  options?: SecondParameter<typeof axiosForReactQueryInstance>
) => {
  return axiosForReactQueryInstance<ApiResponse1SystemString>(
    { url: `/api/Buh/create-accurals`, method: 'PUT', params },
    options
  );
};

export const getPutApiBuhCreateAccuralsMutationOptions = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiBuhCreateAccurals>>,
    TError,
    { params?: PutApiBuhCreateAccuralsParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosForReactQueryInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiBuhCreateAccurals>>,
  TError,
  { params?: PutApiBuhCreateAccuralsParams },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiBuhCreateAccurals>>,
    { params?: PutApiBuhCreateAccuralsParams }
  > = (props) => {
    const { params } = props ?? {};

    return putApiBuhCreateAccurals(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiBuhCreateAccuralsMutationResult = NonNullable<Awaited<ReturnType<typeof putApiBuhCreateAccurals>>>;

export type PutApiBuhCreateAccuralsMutationError = ErrorType<unknown>;

/**
 * @summary Сделать начисления по всем планам начислений на текущий день (только по рабочим ОСИ)
 */
export const usePutApiBuhCreateAccurals = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiBuhCreateAccurals>>,
    TError,
    { params?: PutApiBuhCreateAccuralsParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosForReactQueryInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof putApiBuhCreateAccurals>>,
  TError,
  { params?: PutApiBuhCreateAccuralsParams },
  TContext
> => {
  const mutationOptions = getPutApiBuhCreateAccuralsMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Сделать начисления по всем планам начислений
 */
export const putApiBuhCreateAccuralsInCustomPeriod = (
  params?: PutApiBuhCreateAccuralsInCustomPeriodParams,
  options?: SecondParameter<typeof axiosForReactQueryInstance>
) => {
  return axiosForReactQueryInstance<ApiResponse1SystemString>(
    { url: `/api/Buh/create-accurals-in-custom-period`, method: 'PUT', params },
    options
  );
};

export const getPutApiBuhCreateAccuralsInCustomPeriodMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiBuhCreateAccuralsInCustomPeriod>>,
    TError,
    { params?: PutApiBuhCreateAccuralsInCustomPeriodParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosForReactQueryInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiBuhCreateAccuralsInCustomPeriod>>,
  TError,
  { params?: PutApiBuhCreateAccuralsInCustomPeriodParams },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiBuhCreateAccuralsInCustomPeriod>>,
    { params?: PutApiBuhCreateAccuralsInCustomPeriodParams }
  > = (props) => {
    const { params } = props ?? {};

    return putApiBuhCreateAccuralsInCustomPeriod(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiBuhCreateAccuralsInCustomPeriodMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiBuhCreateAccuralsInCustomPeriod>>
>;

export type PutApiBuhCreateAccuralsInCustomPeriodMutationError = ErrorType<unknown>;

/**
 * @summary Сделать начисления по всем планам начислений
 */
export const usePutApiBuhCreateAccuralsInCustomPeriod = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiBuhCreateAccuralsInCustomPeriod>>,
    TError,
    { params?: PutApiBuhCreateAccuralsInCustomPeriodParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosForReactQueryInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof putApiBuhCreateAccuralsInCustomPeriod>>,
  TError,
  { params?: PutApiBuhCreateAccuralsInCustomPeriodParams },
  TContext
> => {
  const mutationOptions = getPutApiBuhCreateAccuralsInCustomPeriodMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Сделать акты за год и месяц
 */
export const putApiBuhCreateActs = (
  params?: PutApiBuhCreateActsParams,
  options?: SecondParameter<typeof axiosForReactQueryInstance>
) => {
  return axiosForReactQueryInstance<ApiResponse1SystemString>(
    { url: `/api/Buh/create-acts`, method: 'PUT', params },
    options
  );
};

export const getPutApiBuhCreateActsMutationOptions = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiBuhCreateActs>>,
    TError,
    { params?: PutApiBuhCreateActsParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosForReactQueryInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiBuhCreateActs>>,
  TError,
  { params?: PutApiBuhCreateActsParams },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiBuhCreateActs>>,
    { params?: PutApiBuhCreateActsParams }
  > = (props) => {
    const { params } = props ?? {};

    return putApiBuhCreateActs(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiBuhCreateActsMutationResult = NonNullable<Awaited<ReturnType<typeof putApiBuhCreateActs>>>;

export type PutApiBuhCreateActsMutationError = ErrorType<unknown>;

/**
 * @summary Сделать акты за год и месяц
 */
export const usePutApiBuhCreateActs = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiBuhCreateActs>>,
    TError,
    { params?: PutApiBuhCreateActsParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosForReactQueryInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof putApiBuhCreateActs>>,
  TError,
  { params?: PutApiBuhCreateActsParams },
  TContext
> => {
  const mutationOptions = getPutApiBuhCreateActsMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Создать массово ЭСФ по актам за указанным месяц
 */
export const putApiBuhCreateEsfs = (
  params?: PutApiBuhCreateEsfsParams,
  options?: SecondParameter<typeof axiosForReactQueryInstance>
) => {
  return axiosForReactQueryInstance<ApiResponse1SystemString>(
    { url: `/api/Buh/create-esfs`, method: 'PUT', params },
    options
  );
};

export const getPutApiBuhCreateEsfsMutationOptions = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiBuhCreateEsfs>>,
    TError,
    { params?: PutApiBuhCreateEsfsParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosForReactQueryInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiBuhCreateEsfs>>,
  TError,
  { params?: PutApiBuhCreateEsfsParams },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiBuhCreateEsfs>>,
    { params?: PutApiBuhCreateEsfsParams }
  > = (props) => {
    const { params } = props ?? {};

    return putApiBuhCreateEsfs(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiBuhCreateEsfsMutationResult = NonNullable<Awaited<ReturnType<typeof putApiBuhCreateEsfs>>>;

export type PutApiBuhCreateEsfsMutationError = ErrorType<unknown>;

/**
 * @summary Создать массово ЭСФ по актам за указанным месяц
 */
export const usePutApiBuhCreateEsfs = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiBuhCreateEsfs>>,
    TError,
    { params?: PutApiBuhCreateEsfsParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosForReactQueryInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof putApiBuhCreateEsfs>>,
  TError,
  { params?: PutApiBuhCreateEsfsParams },
  TContext
> => {
  const mutationOptions = getPutApiBuhCreateEsfsMutationOptions(options);

  return useMutation(mutationOptions);
};
